.\" Manpage for zypper-upgraderepo.
.TH man 8 "31 Jan 2023" "1.8.0" "zypper-upgraderepo man page"
.SH NAME
zypper-upgraderepo \- check and upgrade the repository list
.SH SYNOPSIS
zypper upgraderepo <operation> [<options>]
.SH DESCRIPTION
.PP
zypper-upgraderepo helps to check and upgrade the repository list
in order to provide a smoother way during the upgrading procedure
from command line, but is also useful to detect problems during regular
updating operations.
.SH OPERATIONS
.TP
.B  -b, --backup PATH
Create an archive containing the repository folder under the specified PATH.
.TP
.B  -c, --check-current
Check for the availability of the current repositories.
.TP
.B  -n, --check-next
Check for the availability of the next version repositories.
.TP
.B  -l, --check-last
Check for the availability of the last version repositories.
.TP
.B  -C, --check-for VERSION
Check for the availability of the given repositories VERSION.
.TP
.B  -R, --reset
Reset the upgraded repositories to the current OS version, root permissions required.
.TP
.B  -t, --update
Update the repositories to the current OS version
.TP
.B  -u, --upgrade
Upgrade the repositories to the next version, root permissions required.
.TP
.B  -U, --upgrade-to VERSION
Upgrade the repositories to the given VERSION, root permissions required.
.TP
.B  -L, --upgrade-to-last
Upgrade the repositories to the last version, root permissions required.
.TP
.B  -s, --status
Print the version status of the current and available openSUSE releases.
.TP
.SH OPTIONS
.TP
.B  --allow-unstable
Consider the unstable version a stable release to upgrade to.
.TP
.B  --no-name
Don't upgrade the repository's name.
.TP
.B  --no-alias
Don't upgrade repository's alias.
.TP
.B  --no-hint
Don't look for an alternative url when the interpolated one is not found.
.TP
.B  --override-url NUMBER,URL
Override the URL for the repository referenced by NUMBER in the checking table.
.TP
.B  --load-overrides FILENAME
Load the URLs to override from FILENAME
.TP
.B  --exit-on-fail
Exit with a properly runlevel when an error is met.
.TP
.B  --timeout SECONDS
Adjust the waiting SECONDS before to raise a server timeout error.
.SH FILTER OPTIONS
.TP
.B  --only-enabled
Include only the enabled repositories to check or upgrade. By default all
repositories are included.
.TP
.B  --only-repo <NUMBER|NAME|@ALIAS|#URL|&ANY>[,NUMBER2|NAME2|@ALIAS2|#URL2|&ANY2,...]
Include only the repositories specified by a NUMBER or a string matching the
NAME, @ALIAS, #URL, or &ANY of them
.TP
.B  --only-invalid
Show only invalid repositories.
.TP
.B --only-protocols <PROTOCOL>[,<PROTOCOL2>,...]
Include only the repositories having their protocol matching the list (i.e. https,http,dir)
.SH VIEW OPTIONS
.TP
.B  --sort-by-alias
Sort the repositories by alias (Default).
.TP
.B  --sort-by-name
Sort the repositories by name.
.TP
.B  --sort-by-priority
Sort the repositories by priority.
.TP
.B  --ini
Show the output as ini format.
.TP
.B  --quiet
Show only error messages.
.TP
.B  --report
Show the output as report.
.PP
The \fB\-\-override\-url\fR option can appear as many times as needed however, exporting the
list of invalid repos with \fB\-\-only\-invalid\fR and the \fB\-\-ini\fR option makes the whole
process more comfortable.
The list of overriden URLs can be imported with the \fB\-\-load-overrides\fR option.
.SS Exit Status:
.TP
0
all OK,
.TP
1
general error,
.TP
2
the system is already upgraded,
.TP
4
not valid permissions while writing the repositories,
.TP
5
a package management application is running,
.TP
6
no connection,
.TP
7
can't find an alternative URL,
.TP
8
an override URL is missing in the ini file,
.TP
9
the old_url field in the ini file doesn't match with the real repo URL;
.TP
11
no unstable version is available.
.TP
.SH SEE ALSO
zypper(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Fabio Mucciante <fabio.mucciante@gmail.com>
