.\" Manpage for zypper-upgraderepo.
.TH man 8 "20 Dec 2018" "1.2.0" "zypper-upgraderepo man page"
.SH NAME
zypper-upgraderepo \- check and upgrade the repository list
.SH SYNOPSIS
zypper upgraderepo <operation> [<options>]
.SH DESCRIPTION
zypper-upgraderepo helps to check and upgrade the repository list
  in order to provide a smoother way during the upgrading procedure 
  from command line, but is also useful to detect problems during regular
  updating operations.
.SH OPERATIONS
.TP
.B  -b, --backup PATH
Backup all the repository folder under the specified PATH.
.TP
.B  -c, --check-current
Check the availability for the installed repositories.
.TP
.B  -N, --check-next
Check the availability for the next version of installed repositories.
.TP
.B  -C, --check-to VERSION
Check the availability for the given VERSION of openSUSE repositories.
.TP
.B  -u, --upgrade
Upgrade the repositories to the next version, root permissions required.
.TP
.B  -U, --upgrade-to VERSION
Upgrade the repositories to the given VERSION, root permissions required.
.SH OPTIONS
.TP
.B  --only-enabled
Include only the enabled repositories to check or upgrade. By default all
repositories are included.
.TP
.B  --only-repo NUMBER[,NUMBER2,...]
Include only the repositories specified by their number during  the check or
upgrade operation.
.TP
.B  --override-url NUMBER,URL
Override the URL for the repository referenced by NUMBER in the checking table.
.TP
.B  --no-name
Don't upgrade the repository's name.
.TP
.B  --no-alias
Don't upgrade repository's alias.
.TP
.B  --no-hint
Don't look for an alternative url when the interpolated one is not found.
.TP
.B  --timeout SECONDS
Adjust the waiting SECONDS before to raise a server timeout error.
.SH VIEW OPTIONS
.TP
.B  --sort-by-alias
Sort the repositories by alias (Default)
.TP
.B  --sort-by-name
Sort the repositories by name
.TP
.B  --sort-by-priority
Sort the repositories by priority
.TP
.B  --report
Show the data as report
.SH RETURN VALUE
zypper upgraderepo returns 0 on success, 1 if some error occurred.
.SH SEE ALSO
zypper(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Fabio Mucciante <fabio.mucciante@gmail.com>
